### ISSUE TITLE
[documentation] Comparison to `iotop` rather than `top`?

### ISSUE THREAD

**Issue by m-ueberall** [asomers/ztop#2]
It says _"`ztop` is like `top`"_, but wouldn't it make more sense to compare it to `iotop` here?

**Comment by asomers** [comment]
Sure, you could compare it to `iotop`.  But `iotop` is Linux-specific, whereas everybody is familiar with `top`.  I could've compared it to `top -mio`, `bpytop`, or various other programs, but `top` is the familiar granddaddy that every other activity monitor tries to imitate.
